name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

      - name: Use Node.js version 20 via NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install --lts
          nvm use --lts
          node -v

      - name: Install dependencies
        run: yarn install

      - name: Run yarn upgrade-interactive
        run: yarn upgrade --latest

      - name: Install updated dependencies
        run: yarn install

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: upgrade dependencies' || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-dependencies
          title: 'chore: upgrade dependencies'
          body: 'Automatically generated by GitHub Action to update dependencies.'
          commit-message: 'chore: upgrade dependencies'
          labels: dependencies
          token: ${{ secrets.ACTIONS_PAT }}
